#'NeosRulez.React.CookieOptIn:Mixin.CookieContentSettings':
#  abstract: true
#  ui:
#    inspector:
#      tabs:
#        neosrulez_react_cookieoptin:
#          label: i18n
#          position: 99
#          icon: 'fas fa-cookie-bite'
#      groups:
#        neosrulez_react_cookieoptin_content_settings:
#          label: i18n
#          icon: 'fas fa-cookie-bite'
#          tab: 'neosrulez_react_cookieoptin'
#          position: 10
#          collapsed: false
#  properties:
#    cookie_group:
#      type: string
#      ui:
#        label: i18n
#        reloadIfChanged: true
#        inspector:
#          group: 'neosrulez_react_cookieoptin_content_settings'
#          editor: Neos.Neos/Inspector/Editors/SelectBoxEditor
#          editorOptions:
#            allowEmpty: true
#            dataSourceIdentifier: neosrulez-react-cookieoptin-cookiegroups